### ISSUE TITLE
When a rocket is fired from a rocket launcher, it is briefly visible under the island

### ISSUE THREAD

**Issue by erlehmann** [evanbowman/skyland#3]
Mednafen 1.22.1
ROM CRC 0x9ab2712a

**Comment by erlehmann** [comment]
Also, when the rocket comes down, it is briefly visible under the enemy island.

**Comment by evanbowman** [comment]
Fixed in the latest version
https://github.com/evanbowman/skyland/releases/tag/2021.11.12.0
