### ISSUE TITLE
Flag tile overwrites rocket launcher tile

### ISSUE THREAD

**Issue by erlehmann** [evanbowman/skyland#4]
Screenshot: https://mister-muffin.de/p/H9_Y.png

**Comment by evanbowman** [comment]
Thanks for reporting these issues, I'll try to fix them soon!

**Comment by evanbowman** [comment]
Out of curiosity, what was underneath the missile-silo? It's floating, correct? The block beneath it was salvaged or destroyed or something? Probably an edge-case that I didn't think of.

**Comment by evanbowman** [comment]
Ah yes, that's what it is, I reproduced the issue. An empty slot between a block and a roof tile results in an overlapping flag sometimes. Should be easy to fix.

**Comment by evanbowman** [comment]
Fixed in the latest version:
https://github.com/evanbowman/skyland/releases/tag/2021.11.12.0
