### ISSUE TITLE
Crash when finishing "lemon tree" quest

### ISSUE THREAD

**Issue by DMeisei** [evanbowman/skyland#6]
Love the game and I been playing it lately on my modded GBA with flash card everdrive x5 mini.
The game crash with a red screen and show "invalid quest marker", need to reboot the game.

- Version: https://skylandgame.io/beta/
- Mode: adventure
- Difficulty: Beginner
- Location: Zone 1 or 2, right after reaching the X mark of the "Lemon tree delivery" quest
- Scenario: I finish this quest a few time, crashed 2 times and 1 was success. In the success run of that quest I manage to preserve all of the tree. But the 2 times I crash was when I lost a few tree, not sure if it have anything to do with the crashing but that's all I could remember.

Good luck with the game and I look forward to playing or buying the finish product.

**Comment by evanbowman** [comment]
Thank you for finding and reporting this bug! I'm on vacation for a few weeks, I will look into it when I'm home.

**Comment by evanbowman** [comment]
I played around with the code a bit today and couldn't reproduce the issue unfortunately. I reverted some recent changes to the quest system, maybe it'll resolve the problem. I've published a new release rom to the beta download page. If the issue occurs again, please send me your save file if possible, and I will investigate further.

**Comment by evanbowman** [comment]
I will leave this issue open until I can reproduce the problem and resolve the bug.

**Comment by DMeisei** [comment]
Understood, I will try to reproduce the bug and provide a save file.

**Comment by evanbowman** [comment]
Great, thanks for your help! No pressure, just try to keep the save file and send it over if the issue comes up again

**Comment by DMeisei** [comment]
Since we are talking about save file, I have a question.
I am playing on a GBA Everdrive x5 mini flash card on a screen modded AGB, using SRam rom setting.
First playthrough, I saved in Adventure mode (Beginner) after moving through a few stage.
Second playthrough, I started where I saved on the first playthrough, but I shut the GBA off before saving.
Third playthrough, I lost all my process. 

Is this intended? Should I always save whenever I stop playing? Or was it the Evedrive x5, rom setting?

**Comment by evanbowman** [comment]
Yeah, this is intended behavior actually. I think the game would be less enjoyable if you could turn off the game and repeatedly retry if you make a mistake, but I'd be open to changing the logic to preserve saves. The game intentionally marks a previous save as invalid when you load a saved game, and expects you to save again. Maybe for beginner difficulty, I should allow people to preserve saves. The game also has a hibernate feature to send the gba into low sleep mode, available on the start menu.

**Comment by DMeisei** [comment]
Ah thanks for the response, I was confuse a bit thinking it was my flash card.

**Comment by evanbowman** [comment]
Thanks for the feedback! I'll put a message into the game explaining the saving process.

**Comment by DMeisei** [comment]
I couldn't re-produce the issue anymore, or maybe I am just unlucky. Guess I will close this issue, if I get the error again and have a the save file I will open a new issue.

**Comment by evanbowman** [comment]
Thank you very much for raising the issue, please let me know about any bugs you find in the future!
